name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip git python3-pip \
            openjdk-17-jdk \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libgstreamer1.0 libmtdev-dev \
            libgl1-mesa-dev libgles2-mesa-dev \
            xclip xsel libjpeg-dev \
            libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer

      - name: Install Android SDK Tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: alshams-billing-apk
          path: bin/*.apk
